%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\sanju\Desktop\Project\100_data_Webometrics.xlsx
%    Worksheet: Binary_Data
%    Worksheet: Trend
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2026/02/16 00:45:47

%% Import the data
[~, ~, Identifier] = xlsread('C:\Users\sanju\Desktop\Project\100_data_Webometrics.xlsx','Binary_Data','B2:AB101');
[~, ~, Statement] = xlsread('C:\Users\sanju\Desktop\Project\100_data_Webometrics.xlsx','Binary_Data','AC2:AR101');
[~, ~, Trend] = xlsread('C:\Users\sanju\Desktop\Project\100_data_Webometrics.xlsx','Trend','B2:D101');

%% Create output variable
Dataset_Identifier = reshape([Identifier{:}],size(Identifier));
Dataset_Statement = reshape([Statement{:}],size(Statement));
Dataset_Trend = reshape([Trend{:}],size(Trend));

%% Clear temporary variables
clearvars Identifier;
clearvars Statement;
clearvars Trend;